# Generated by Django 5.0.6 on 2025-02-19 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maintenancerecord",
            name="equipment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maintenance_records",
                to="equipment.equipment",
                verbose_name="设备",
            ),
        ),
    ]
