# Generated by Django 5.0.6 on 2025-02-23 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0003_alter_maintenancerecord_equipment"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="importance",
            field=models.CharField(
                choices=[("high", "高"), ("medium", "中"), ("low", "低")],
                default="medium",
                max_length=10,
                verbose_name="重要程度",
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="maintenance_cycle",
            field=models.IntegerField(
                choices=[(30, "每月"), (90, "每季度"), (180, "每半年"), (365, "每年")],
                default=365,
                verbose_name="保养周期(天)",
            ),
        ),
    ]
