# Generated by Django 5.0.6 on 2025-02-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0004_equipment_importance_equipment_maintenance_cycle"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="供应商名称")),
                (
                    "address",
                    models.CharField(max_length=500, verbose_name="供应商地址"),
                ),
                ("repair_scope", models.TextField(verbose_name="维修范围")),
                ("repair_equipment", models.TextField(verbose_name="维修台架")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "供应商",
                "verbose_name_plural": "供应商",
                "ordering": ["-created_at"],
                "permissions": [("can_manage_supplier", "Can manage supplier")],
            },
        ),
    ]
