# Generated by Django 5.0.6 on 2025-02-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0005_supplier"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="contact_person",
            field=models.CharField(default=1, max_length=100, verbose_name="联系人"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="supplier",
            name="contact_phone",
            field=models.CharField(default=1, max_length=20, verbose_name="联系电话"),
            preserve_default=False,
        ),
    ]
