# Generated by Django 4.2.13 on 2024-09-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='委托部门')),
                ('department_leader', models.CharField(max_length=100, verbose_name='部门领导')),
                ('tech_center_leader', models.CharField(max_length=100, verbose_name='技术中心领导')),
            ],
        ),
        migrations.CreateModel(
            name='Outlines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_style', models.CharField(max_length=30)),
                ('project', models.CharField(max_length=30)),
                ('outline_num', models.CharField(max_length=100)),
                ('outline_name', models.CharField(max_length=150)),
                ('editor', models.CharField(max_length=30)),
                ('save_date', models.DateField()),
                ('outline_status', models.CharField(max_length=30)),
                ('remark', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
