# Generated by Django 4.2.13 on 2024-09-09 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprehensive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='projects',
            field=models.CharField(default=1, max_length=255, verbose_name='负责项目'),
            preserve_default=False,
        ),
    ]
