# Generated by Django 4.2.13 on 2024-09-09 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprehensive', '0002_department_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_email',
            field=models.CharField(default=1, max_length=50, verbose_name='部门领导邮箱'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='leader_email',
            field=models.CharField(default=1, max_length=50, verbose_name='分管领导邮箱'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='tech_center_leader',
            field=models.CharField(max_length=100, verbose_name='部门分管领导'),
        ),
    ]
