# Generated by Django 4.2.13 on 2024-09-03 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('birth_date', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('entry_date', models.DateField()),
                ('department', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
                ('expertise', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('potential', models.CharField(max_length=10)),
                ('skill', models.CharField(max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='persons/')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill1', models.IntegerField(default=0)),
                ('skill2', models.IntegerField(default=0)),
                ('skill3', models.IntegerField(default=0)),
                ('skill4', models.IntegerField(default=0)),
                ('skill5', models.IntegerField(default=0)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skill_data', to='persons.person')),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_name', models.CharField(max_length=50)),
                ('performance1', models.IntegerField(default=0)),
                ('performance2', models.IntegerField(default=0)),
                ('performance3', models.IntegerField(default=0)),
                ('performance4', models.IntegerField(default=0)),
                ('performance5', models.IntegerField(default=0)),
                ('performance6', models.IntegerField(default=0)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_data', to='persons.person')),
            ],
        ),
    ]
