# Generated by Django 4.2.13 on 2024-09-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_overtimeapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtimeapplication',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='overtimeapplication',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
