# Generated by Django 5.0.6 on 2024-09-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persons", "0003_alter_overtimeapplication_end_time_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="overtimeapplication",
            old_name="employee_name",
            new_name="overtime_employee_name",
        ),
        migrations.RemoveField(
            model_name="overtimeapplication",
            name="reason",
        ),
        migrations.AddField(
            model_name="overtimeapplication",
            name="submitter_name",
            field=models.CharField(default="2024-09-13", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="overtimeapplication",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
