# Generated by Django 5.0.6 on 2024-09-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "persons",
            "0004_rename_employee_name_overtimeapplication_overtime_employee_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="overtimeapplication",
            name="application_date",
            field=models.DateField(default="2024-09-13"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="overtimeapplication",
            name="reason",
            field=models.TextField(default="2024-09-13"),
            preserve_default=False,
        ),
    ]
