# Generated by Django 5.0.6 on 2024-09-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persons", "0005_overtimeapplication_application_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="overtimeapplication",
            name="application_number",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
