# Generated by Django 5.0.6 on 2024-09-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persons", "0006_overtimeapplication_application_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="overtimeapplication",
            name="department_leader_comments",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="overtimeapplication",
            name="line_leader_comments",
            field=models.TextField(blank=True, null=True),
        ),
    ]
