# Generated by Django 5.0.6 on 2024-09-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persons", "0007_overtimeapplication_department_leader_comments_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="overtimeapplication",
            name="status",
            field=models.CharField(default="未批准", max_length=20),
        ),
    ]
