# Generated by Django 5.0.6 on 2024-09-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persons", "0008_overtimeapplication_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="overtimeapplication",
            name="department_leader_approval_status",
            field=models.CharField(
                choices=[
                    ("Pending", "待审批"),
                    ("Approved", "已审批"),
                    ("Rejected", "已拒绝"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="overtimeapplication",
            name="line_leader_approval_status",
            field=models.CharField(
                choices=[
                    ("Pending", "待审批"),
                    ("Approved", "已审批"),
                    ("Rejected", "已拒绝"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="overtimeapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "待审批"),
                    ("Approved", "已审批"),
                    ("Rejected", "已拒绝"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
    ]
