# Generated by Django 4.2.13 on 2024-09-14 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0009_overtimeapplication_department_leader_approval_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overtimeapplication',
            name='department_leader_approval_status',
        ),
        migrations.RemoveField(
            model_name='overtimeapplication',
            name='line_leader_approval_status',
        ),
        migrations.RemoveField(
            model_name='overtimeapplication',
            name='status',
        ),
        migrations.AddField(
            model_name='overtimeapplication',
            name='department_leader_approval',
            field=models.CharField(choices=[('pending', '待审批'), ('approved', '已通过'), ('rejected', '未通过')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='overtimeapplication',
            name='line_leader_approval',
            field=models.CharField(choices=[('pending', '待审批'), ('approved', '已通过'), ('rejected', '未通过')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='overtimeapplication',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
