# Generated by Django 4.2.13 on 2024-09-14 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0010_remove_overtimeapplication_department_leader_approval_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='overtimeapplication',
            options={'permissions': [('can_approve_line_leader', 'Can approve as line leader'), ('can_approve_department_leader', 'Can approve as department leader')]},
        ),
        migrations.RemoveField(
            model_name='overtimeapplication',
            name='rejection_reason',
        ),
        migrations.AlterField(
            model_name='overtimeapplication',
            name='department_leader_approval',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='overtimeapplication',
            name='line_leader_approval',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
