# Generated by Django 4.2.13 on 2024-09-14 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0011_alter_overtimeapplication_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimeapplication',
            name='department_leader_rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='overtimeapplication',
            name='line_leader_rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
