# Generated by Django 5.0.6 on 2024-09-30 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "persons",
            "0012_overtimeapplication_department_leader_rejection_reason_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="overtimeapplication",
            name="department_leader_comments",
        ),
        migrations.RemoveField(
            model_name="overtimeapplication",
            name="line_leader_comments",
        ),
    ]
