# Generated by Django 5.0.6 on 2025-02-17 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "persons",
            "0013_remove_overtimeapplication_department_leader_comments_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="overtimeapplication",
            options={
                "permissions": [
                    ("can_approve_line_leader", "Can approve as line leader"),
                    (
                        "can_approve_department_leader",
                        "Can approve as department leader",
                    ),
                    (
                        "can_approve_general_management",
                        "Can approve as general management",
                    ),
                ]
            },
        ),
        migrations.AddField(
            model_name="overtimeapplication",
            name="general_management_approval",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="overtimeapplication",
            name="general_management_rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
